### PR TITLE
Move to go module, fix cli package reference

### PR DESCRIPTION
**Pull request by amake**
Pull requests #50 and #52 opened up a can of worms:

1. You are now using `github.com/urfave/cli` v2.0.0 but this is not reflected in the glide files, so for instance I have a hard time updating the MacPorts port because it's no longer clear what your dependencies are pinned to
2. Trying to update the glide files fails because, as best I can tell, some dependencies have moved to the modern go module system, and glide can't understand it:

    ```
    % glide cc
    [INFO]	Glide cache has been cleared.
    % glide up
    [INFO]	Downloading dependencies. Please wait...
    [INFO]	--> Fetching gopkg.in/yaml.v2
    [INFO]	--> Fetching github.com/codegangsta/cli
    [INFO]	--> Fetching github.com/mattn/go-sqlite3
    [INFO]	--> Fetching golang.org/x/net
    [INFO]	--> Fetching github.com/andybalholm/cascadia
    [INFO]	Resolving imports
    [INFO]	--> Fetching github.com/urfave/cli
    [INFO]	--> Fetching github.com/cpuguy83/go-md2man
    [ERROR]	Error scanning github.com/cpuguy83/go-md2man/v2/md2man: cannot find package "." in:
        /Users/amake/.glide/cache/src/https-github.com-cpuguy83-go-md2man/v2/md2man
    [ERROR]	Failed to retrieve a list of dependencies: Error resolving imports
    ```
3. The only reasonable solution seems to be moving this project to go modules as well. In that case, the import for `github.com/urfave/cli` needs to be corrected to `"github.com/urfave/cli/v2"`.

This PR moves to the go module system and fixes the import path. I did it by

1. Running `go mod init`, which knows how to migrate from glide 
2. Fixing the import path
3. Running `go mod tidy`

### CODE REVIEW

**Comment by iwittkau** [comment]
This would also help fixing the homebrew formula: https://github.com/technosophos/dashing/pull/53

**Comment by beauhoyt** [comment]
Hi @technosophos can you let us know what you think about this pull request. It would greatly help resolve issues we're having merging golang-1.13.5 in homebrew (https://github.com/Homebrew/homebrew-core/pull/47510). Thanks~ ^_^

**Comment by technosophos** [comment]
Thanks for fixing this. I'm not a fan of Go modules, nor of the way the Go team managed this. But they are clearly unavoidable at this point. So I will move forward with them.

**Comment by beauhoyt** [comment]
@technosophos Thanks man :D

**Pull request merged**
