### PR TITLE
Update CLI API calls to 2.0

### PR DESCRIPTION
**Pull request by tvolkert**
Fixes https://github.com/technosophos/dashing/issues/51

### CODE REVIEW

**Comment by tvolkert** [comment]
@technosophos please merge this ASAP, as our docker build is broken until this is fixed.

Thanks!

**Comment by tvolkert** [comment]
@christopherfujino FYI

**Comment by technosophos** [comment]
Are you using Glide to build this or another build tool?

**Comment by tvolkert** [comment]
I'm a Go noob, so I flubbed my way through it 😄 

I looked at the migration guide for CLI 2.0, and I pushed updates to my fork and ran `go get -u github.com/tvolkert/dashing` to test the fixes.

**Comment by tvolkert** [comment]
Thanks!!

**Pull request merged**
